name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: build
      run: nix build .
    - name: docker
      run: |
        nix build .#docker
        cp result chronocat.tar.gz
    - uses: actions/upload-artifact@v4
      with:
        name: image
        path: chronocat.tar.gz